name: Raspberry Pi Containerdisk Builder

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  publish-trixie-containerdisk:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and push Trixie containerdisk
        env:
          BUILD_TARGET: 'trixie'
        run: bash ./build-raspios-lite-containerdisk.sh

  publish-bookworm-containerdisk:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and push Bookworm containerdisk
        env:
          BUILD_TARGET: 'bookworm'
        run: bash ./build-raspios-lite-containerdisk.sh
